<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ReadableNumbers</AssemblyName>
    <RootNamespace>ReadableNumbers</RootNamespace>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Version>1.1.0</Version>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>F:\SteamLibrary\steamapps\common\Shadow Dungeon\BepInEx\core\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>F:\SteamLibrary\steamapps\common\Shadow Dungeon\BepInEx\core\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>F:\SteamLibrary\steamapps\common\Shadow Dungeon\Shadow Dungeon_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="FinkFramework.Runtime">
      <HintPath>F:\SteamLibrary\steamapps\common\Shadow Dungeon\Shadow Dungeon_Data\Managed\FinkFramework.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>F:\SteamLibrary\steamapps\common\Shadow Dungeon\Shadow Dungeon_Data\Managed\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>F:\SteamLibrary\steamapps\common\Shadow Dungeon\Shadow Dungeon_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>F:\SteamLibrary\steamapps\common\Shadow Dungeon\Shadow Dungeon_Data\Managed\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>F:\SteamLibrary\steamapps\common\Shadow Dungeon\Shadow Dungeon_Data\Managed\UnityEngine.UIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>F:\SteamLibrary\steamapps\common\Shadow Dungeon\Shadow Dungeon_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
